name: Docker Image
on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/docker.yml
      - .dockerignore
      - Dockerfile
      - go.mod
      - go.sum
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{github.repository_owner}}/drone-crowdin-v2:latest
          platforms: linux/386,linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/arm/v5

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
